Update readme and deploy script.
veracruz-project/video-object-detection pull request #8
Opened 2023-12-08 15:00 UTC by ShaleXIONG

Update the readme and deploy script.
- Replace all absolute remote path to relative path under the current dir `.`.
- Update the generate policy script.

2023-12-08 17:32 UTC, gbryant-arm requested changes

2023-12-08 17:32 UTC, gbryant-arm commented on deploy_linux_pnm.sh
> +    --result "./$OUTPUT_DIR/prediction.0.jpg=prediction.0.jpg" \
Why fetching one single frame? There could be several IIRC

2023-12-08 17:32 UTC, gbryant-arm commented on deploy_linux_pnm.sh
Have you tried running this script?

2023-12-08 17:32 UTC, gbryant-arm commented on deploy_linux_wasm.sh
> -    --enclave-debug-mode \
Why removing these two parameters? Why here and not in `deploy_linux_pnm.sh` too?

2023-12-08 17:32 UTC, gbryant-arm commented on deploy_linux_wasm.sh
> -for ((i=0;i<frame_count;i++)); do
Same question as in `deploy_linux_pnm.sh`

2023-12-08 17:32 UTC, gbryant-arm commented on deploy_nitro_pnm.sh
> -for ((i=0;i<frame_count;i++)); do
Same as above

2023-12-08 17:32 UTC, gbryant-arm commented on deploy_nitro_wasm.sh
> -for ((i=0;i<frame_count;i++)); do
Same

2023-12-11 10:43 UTC, ShaleXIONG commented on deploy_linux_pnm.sh
> +    --result "./$OUTPUT_DIR/prediction.0.jpg=prediction.0.jpg" \
The script used to rely on `stdout` to fetch the number of frame. While the new engine does not have special file for `stdout` you can directly read from. I am not sure how to change the source code to output the number of frame implicit to a file.

2023-12-11 10:44 UTC, ShaleXIONG commented on deploy_linux_pnm.sh
I did not try. Any guide how I should execute this script?

2023-12-11 10:44 UTC, ShaleXIONG commented on deploy_linux_wasm.sh
> -    --enclave-debug-mode \
Some flags are no longer used.

2024-01-09 15:58 UTC, gbryant-arm commented on deploy_linux_pnm.sh
> +    --result "./$OUTPUT_DIR/prediction.0.jpg=prediction.0.jpg" \
You could change things here:
https://github.com/veracruz-project/openh264-dec/blob/dce3829f14a8aa7b25b7e010ba2beb07390bf527/src/h264dec.cpp#L473C51-L473C58
and dump the info to a file, for example

2024-04-05 15:19 UTC, gbryant-arm approved these changes
LGTM

2024-04-05 15:41 UTC, merged